export const actionDispatch = {
    ADD_LIST: "ADD_LIST",
    ADD_CARD: "ADD_CARD",
    REMOVE_LIST: "REMOVE_LIST",
    REMOVE_CARD: "REMOVE_CARD",
    ORDER_CARD: "ORDER_CARD",
    MOVE_CARD_FROM_LIST: "MOVE_CARD_FROM_LIST",
    ORDER_LIST: "ORDER_LIST"
}